version: "3"

services:
  database:
    container_name: mysql
    image: mysql/mysql-server:latest
    environment:
      MYSQL_DATABASE: algobaro
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin1234
      MYSQL_ROOT_HOST: '%'
      MYSQL_ROOT_PASSWORD: rootpwd
    command:
      - --default-authentication-plugin=mysql_native_password
    ports:
      - 3305:3306
    networks:
      - db_network
    restart: always
  mytamla:
    build: .
    expose:
      - 8080
    depends_on:
      - database

networks:
  db_network:
    driver: bridge
